#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamDroid.ExpandableRecyclerView.Sample.Resource", IsApplication=true)]

namespace XamDroid.ExpandableRecyclerView.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::XamDroid.ExpandableRecyclerView.Resource.Attribute.layoutManager = global::XamDroid.ExpandableRecyclerView.Sample.Resource.Attribute.layoutManager;
			global::XamDroid.ExpandableRecyclerView.Resource.Attribute.reverseLayout = global::XamDroid.ExpandableRecyclerView.Sample.Resource.Attribute.reverseLayout;
			global::XamDroid.ExpandableRecyclerView.Resource.Attribute.spanCount = global::XamDroid.ExpandableRecyclerView.Sample.Resource.Attribute.spanCount;
			global::XamDroid.ExpandableRecyclerView.Resource.Attribute.stackFromEnd = global::XamDroid.ExpandableRecyclerView.Sample.Resource.Attribute.stackFromEnd;
			global::XamDroid.ExpandableRecyclerView.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::XamDroid.ExpandableRecyclerView.Sample.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::XamDroid.ExpandableRecyclerView.Resource.Id.item_touch_helper_previous_elevation = global::XamDroid.ExpandableRecyclerView.Sample.Resource.Id.item_touch_helper_previous_elevation;
			global::XamDroid.ExpandableRecyclerView.Resource.String.library_name = global::XamDroid.ExpandableRecyclerView.Sample.Resource.String.library_name;
			global::XamDroid.ExpandableRecyclerView.Resource.Styleable.RecyclerView = global::XamDroid.ExpandableRecyclerView.Sample.Resource.Styleable.RecyclerView;
			global::XamDroid.ExpandableRecyclerView.Resource.Styleable.RecyclerView_android_orientation = global::XamDroid.ExpandableRecyclerView.Sample.Resource.Styleable.RecyclerView_android_orientation;
			global::XamDroid.ExpandableRecyclerView.Resource.Styleable.RecyclerView_layoutManager = global::XamDroid.ExpandableRecyclerView.Sample.Resource.Styleable.RecyclerView_layoutManager;
			global::XamDroid.ExpandableRecyclerView.Resource.Styleable.RecyclerView_reverseLayout = global::XamDroid.ExpandableRecyclerView.Sample.Resource.Styleable.RecyclerView_reverseLayout;
			global::XamDroid.ExpandableRecyclerView.Resource.Styleable.RecyclerView_spanCount = global::XamDroid.ExpandableRecyclerView.Sample.Resource.Styleable.RecyclerView_spanCount;
			global::XamDroid.ExpandableRecyclerView.Resource.Styleable.RecyclerView_stackFromEnd = global::XamDroid.ExpandableRecyclerView.Sample.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040001
			public const int activity_horizontal_margin = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int activity_vertical_margin = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int CrimeRecyclerView = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int FragmentContainer = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int action_settings = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int child_list_item_crime_date_text_view = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int child_list_item_crime_solved_check_box = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int crime_date = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int crime_solved = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int crime_title = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int myButton = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int parent_list_item_crime_title_text_view = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int parent_list_item_expand_arrow = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivityFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FragmentCrime = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FragmentCrimeList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListItemCrimeChild = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListItemCrimeParent = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int Crime = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060003
			public const int action_settings = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int crime_details_label = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int crime_solved_label = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int crime_title_hint = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int crime_title_label = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int hello = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
